{% set version = "0.7.1" %}

package:
  name: oommfodt
  version: {{ version }}

source:
  fn: oommfodt-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/6c/07/d8e044e9ac7bb1508d038e7e979e69e2ae9bb1cc67d6434d212a0325d8fb/oommfodt-0.7.1.tar.gz
  sha256: ec21c2878c79a562498117bf2d5a5e3e9157daf933c60fde0cbbf4a0976aa110

build:
  number: 0
  script: pip install --no-deps .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pandas

test:
  imports:
    - oommfodt

about:
  home: http://joommf.github.io/
  license: BSD 3-clause
  summary: Reading and analysing OOMMF odt files
  # license_file: LICENSE


