{% set version = "0.1.4" %}

package:
  name: sarge
  version: {{ version }}

source:
  fn: sarge-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/bc/9a/a715357f0f0a394edf964fb52b8b39551b629f4d1c996ade5f600fb3d278/sarge-0.1.4.tar.gz
  sha256: 59f93216723ddd9062d17cbbb90ed9e69267b84825cf0bde0b7f8d934c424823

build:
  number: 0
  script: pip install --no-deps .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - sarge

about:
  home: http://sarge.readthedocs.io/en/latest/
  license: BSD 3-clause
  summary: a wrapper for subprocess for interaction with external applications
  # license_file: LICENSE


