{% set version = "0.5.18" %}

package:
  name: pyvtk
  version: {{ version }}

source:
  fn: pyvtk-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/6a/dc/d5ffc2cc50bdd7a2e7b435655ee5931d614f7c118624dd20c51440c79337/PyVTK-0.5.18.tar.gz
  sha256: 608b509b0da4525ad43078b3a60185c359c16f07a2f6b44fbd6f28fb4b9c4e53

build:
  number: 0
  script: pip install --no-deps .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six
    - numpy
   


test:
  imports:
    - pyvtk

about:
  home: https://github.com/pearu/pyvtk
  license: BSD 3-clause
  summary: manipulating vtk files with Python
  # license_file: LICENSE


