package:
  name: oommf
  version: "12a6"

source:
  git_url: https://github.com/fangohr/oommf

build:
  number: 0

requirements:
  build:
    - tk 8.5*
  run:
    - tk 8.5*

test:
  commands:
    - oommf +version

about:
  home: http://math.nist.gov/oommf/
  license_file: oommf/LICENSE

# vim:set ts=8 sw=2 sts=2 tw=78 et:
