{% set version = "0.1" %}

package:
  name: vectorspector
  version: {{ version }}

source:
  fn: vectorspector-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/5a/fb/227aaae2c8f1d308d3bb830b1bdf57332ddf2ba6a8a86f6e0f55753a4feb/vectorspector-0.1.tar.gz
  sha256: 70a0a664de8ad36b0e42e5bf5e1358d7aaae99c61566d924e9984c43a1013f1b

build:
  number: 0
  script: pip install --no-deps .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - matplotlib
    - scipy
    #- vtk

test:
  imports:
    - vectorspector

about:
  home: https://github.com/davidcortesortuno/vectorspector
  license: BSD 3-clause
  summary: Python library for plotting vector fields from different data sources such as VTK files, numpy arrays, etc.
  # license_file: LICENSE


